config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :settings
  resources :emails
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :setting
  has_many :campaign_mails

  after_create :generate_campaign_mails

  def generate_campaign_mails
    Email.all.each do |email|
      CampaignMail.create campaign_id: self.id, email_id: email.id, status: 0
    end
  end

  def self.emails_processed
    emails_processed = []
    Campaign.all.each do |campaign|
      all = campaign.campaign_mails.count
      processed = campaign.campaign_mails.where(status: 1).count
      emails_processed[campaign.id] = {all: all, processed: processed}
    end
    emails_processed
  end

end

app/models/campaign_mail.rb
class CampaignMail < ApplicationRecord
  belongs_to :campaign
  belongs_to :email

  scope :not_sent, -> { where(status:0) }
end

app/models/email.rb
class Email < ApplicationRecord
  has_many :campaign_mails
  validates_uniqueness_of :email
  validates_format_of :email,:with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def self.create_from_csv(file_path)
    file = File.open(file_path, 'r:ISO-8859-1')
    created_emails = []
    file.each_line do |email|
      email.strip!
      new_mail = Email.new email: email
      if new_mail.save
        created_emails << new_mail
      end
    end
    created_emails
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
    @settings = Setting.all
    @emails_processed = Campaign.emails_processed
  end

  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      render json: @campaign
    else
      render json: @campaign.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    head :no_content
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :content, :setting_id, :subject, :from_name, :from_email)
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    @emails = Email.all
  end

  def create
    if params[:file]
      created_emails = Email.create_from_csv(params[:file].path)
      render json: created_emails
    else
      @email = Email.new(email_params)

      if @email.save
        render json: @email
      else
        render json: @email.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    head :no_content
  end

  private

  def email_params
    params.require(:email).permit(:email)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @settings = Setting.all
  end

  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      render json: @setting
    else
      render json: @setting.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy
    head :no_content
  end

  private

  def setting_params
    params.require(:setting).permit(:name, :host, :user, :password, :port)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/mails_helper.rb
module MailsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/campaigns/index.html.erb
<% content_for :subtitle do %>
  Campaigns
<% end %>
<%= react_component 'Campaigns', { data: @campaigns, settings: @settings, emails_processed: @emails_processed } %>

<script>
  function deleteActivator(){
    how = $("a:contains('Unlicensed Froala Editor')").length;
    if(how>0){
      $("a:contains('Unlicensed Froala Editor')").remove();
    }else{
      setTimeout(deleteActivator, 50);
    }
  }

  function updateFroala(){
    $('#contentInput').val($('#froala').froalaEditor('html.get'))
    setTimeout(updateFroala, 100);
  }

  $(document).ready(function(){
    setTimeout(function(){
      $('#froala').froalaEditor();
      deleteActivator();
      updateFroala();
    }, 500);
  });
</script>

app/views/layouts/_menu.html.erb
<div class="list-group">
  <a class="list-group-item" href="<%= emails_path %>">E-mails</a>
  <a class="list-group-item" href="<%= campaigns_path %>">Campaigns</a>
  <a class="list-group-item" href="<%= settings_path %>">Settings</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Designmail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="#" class="navbar-brand">Dotdesign - Mailer</a>
        </div>
        <% if content_for?(:subtitle) %>
          <div class="navbar-text">
            <span><%= yield(:subtitle) %></span>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render 'layouts/menu' %>
        </div>
        <div class="col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/settings/index.html.erb
<% content_for :subtitle do %>
  Settings
<% end %>

<%= react_component 'Settings', { data: @settings } %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>